### ISSUE TITLE
Travis devel, release failing

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#627]
Since Invenio2 merge #600 Travis builds for `devel`, and `release` keep failing. Related issues: #609 #612.

**Release**
Failing/ errors in tests:
* test_pagination_flow
* test_update_tag_pass
* test_get_tag
* test_detach_tags_from_record_pass
* test_attach_tags_to_record_pass
* test_validation_compare_authors

**Devel**
~~Not going past:~~
```bash
travis_retry pip install -r .travis-$REQUIREMENTS-requirements.txt --allow-all-external --quiet
```

**Comment by jirikuncar** [comment]
Please update to latest `maint-2.0` where it has been fixed.

**Comment by dblommesteijn** [comment]
@emanueldima  can you figure this out? Do we need to merge invenio again?

**Comment by emanueldima** [comment]
I tried using the invenio .travis configuration and setup.py file but the build still fails (see https://travis-ci.org/emanueldima/b2share/builds/59753889). We probably must merge the whole thing. Shouldn't be much work, but I'm wondering why should we do it. Up until now travis didn't help at all but did cost us a lot of time. Maybe we should bother with it when we'll have more tests?

**Comment by jirikuncar** [comment]
If you separate your code from Invenio sources then you don't need to run the whole Invenio testsuite but only your integration tests.

**Comment by dblommesteijn** [comment]
Dependency (flask-admin)[https://github.com/flask-admin/flask-admin] is moved from `mrjoes` to `flask-admin` organisation. Probably `devel` was building correctly because `flask-admin` dep was satisfied before `.travis-devel-requirements.txt` was executed, which was not the case with `release`.

Both tests of `release`, and `devel` are failing the same way (errors listed above).

**Comment by cjhak** [comment]
@dblommesteijn Please make a request for pulling your Travis-fixes to 1.4 branch as well.

**Comment by dblommesteijn** [comment]
@cjhak will do

**Comment by dblommesteijn** [comment]
Travis works for `1.4`, can anyone merge it? Thanks!

**Comment by dblommesteijn** [comment]
Pull-requests: #632 and #633 are failing Travis because they don't have the code fixing the Travis issue.
